/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chaudieregvb7_swing;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author user
 */
public class PanelConsigne extends javax.swing.JPanel {

    /**
     * Creates new form PanelConsigne
     */
    public int _h = -1;
    public PanelConsigne() {
        initComponents();
        this.setSize(34, 508);
        this.setBackground(Color.yellow);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private int _consigne = 21;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        //_consigne = (int)Math.floor( 1.0 -  (_max - _min) * this.getHeight() / evt.getY()     );
        double ratio = 1.0 - (    (0.0 + evt.getY()) / (0.0+this.getHeight())   ); // entre 0 et 1
        double delta_degres = 0.0 + _max - _min;
        double cons = _min + delta_degres*ratio;
        int consigne = (int) Math.ceil(cons);
        if(consigne == getConsigne()) consigne--;
        setConsigne( consigne );
        ((NewJFrame) this.getParent().getParent().getParent().getParent().getParent().getParent().getParent())
                .UpdateConsigneFromPanel(_h);
        //repaint();
    }//GEN-LAST:event_formMousePressed

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        int delta_v = this.getHeight() / (_max - _min);
        Color col = new Color( (_consigne-_min)*20+55, 0, 0);
        if(_consigne == 15)
            this.setBackground(Color.cyan);
        else
            this.setBackground(Color.yellow);
        g.setColor(col);
        g.fillRect(1, this.getHeight() - (_consigne-_min)*delta_v, this.getWidth()-2, (_consigne-_min)*delta_v    );

        g.setColor(Color.black);
        
        for(int j=0; j<this.getHeight(); j++) {
            g.drawLine(0, j*delta_v, this.getWidth()-1, j*delta_v);
        }
    }
    
    public int getConsigne() {
        return _consigne ;
    }
    public void setConsigne(int c) {
        _consigne = c ;
        repaint();
    }
    
    public int _min = 15;
    public int _max = 25;

    public int getMin() {
        return _min;
    }

    public void setMin(int _min) {
        this._min = _min;
    }

    public int getMax() {
        return _max;
    }

    public void setMax(int _max) {
        this._max = _max;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
